import{a as q,S as P,i as p}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();let i=1,h=15;function $(){i+=1}function H(){i=1}async function y(t){const o="46773204-8ec36d0a78d9132ebe706b3ce",r=new URLSearchParams({key:o,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:h});return(await q.get(`https://pixabay.com/api/?${r}`)).data}document.querySelector("body");let v=new P(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,loop:!0});const I=document.querySelector(".form"),g=document.querySelector(".user-input"),l=document.querySelector(".btn-load");function R(){l.style.display="block",console.log("Button shown")}function c(){l.style.display="none",console.log("Button hidden")}c();let a;I.addEventListener("submit",async t=>{if(t.preventDefault(),g.value.trim()?(a=g.value.trim(),H(),l.removeEventListener("click",f)):a=void 0,a){w();try{const o=await y(a);if(L(o,v))R(),l.addEventListener("click",f);else throw new Error("No images found!")}catch{c(),p.error({message:"Sorry, there are no images matching your search query. Please try again!",messageSize:18,messageLineHeight:30,position:"topRight"})}finally{S()}}});async function f(){$(),console.log("Current page:",i);try{w();const t=await y(a);if(t.hits.length===0){c(),p.warning({message:"No more images to load.",messageSize:18,messageLineHeight:30,position:"topRight"});return}L(t,v),setTimeout(()=>{window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})},300),m()}catch(t){console.log(t)}}function m(){const o=document.querySelector(".gallery").getBoundingClientRect();o.height&&o.height}document.addEventListener("scroll",m);m();const b=document.querySelector(".wrapp"),u=document.querySelector(".gallery");function L(t,o){if(t.total===0){u.innerHTML="";return}else{let r=Math.ceil(t.totalHits/h);console.log(r),r===i&&(c(),p.error({message:"We're sorry, but you've reached the end of search results.",messageSize:18,messageLineHeight:30,position:"topRight"})),S();const n=t.hits.map(e=>`<li class="gallery-item"><a href="${e.largeImageURL}" data-source="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
          <div class="wrapp-items">
          <div class="info-item"><p class="bold">Likes</p>
          <p>${e.likes}</p>
          </div>
          <div class="info-item"><p class="bold">Views</p>
          <p>${e.views}</p>
          </div>
          <div class="info-item"><p class="bold">Comments</p>
          <p>${e.comments}</p>
          </div>
          <div class="info-item"><p class="bold">Downloads</p>
          <p>${e.downloads}</p>
          </div>

          </div></li>`).join("");return i!==1?u.insertAdjacentHTML("beforeend",n):u.innerHTML=n,o.refresh(),!0}}function w(){b.style.display="block"}function S(){b.style.display="none"}
//# sourceMappingURL=index.js.map
